default:
 
  #
  # Basic
  #
  server:
    port: 3000
 
  #
  # Log
  #
  log:
    path: logs/logs.log
 
  #
  # Microservice
  #
  microservice:
    basePath: src/utils
    server:
      name: starter/v1
      dependencies: my/other/service/to/monitor/v1
      registrationNetworkInterfacePriority: 
        - en0
        - lo0
 
  #
  # Zookeeper
  #
  zookeeper:
    connectionString: localhost:2181
    retry:
      wait: 1000
      count: 5
 